apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seismic-data-pvc
  namespace: ovdas
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
