---
# ConfigMap: variables de entorno no sensibles
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovdas-config
  namespace: ovdas
data:
  RABBITMQ_URL: "amqp://ovdas:ovdas@rabbitmq:5672/"
  POSTGRES_DSN: "host=postgres port=5432 dbname=ovdas user=ovdas password=ovdas"
  REDIS_URL:    "redis://redis:6379/0"

---
# Secret: credenciales (base64: echo -n 'ovdas' | base64 → b3ZkYXM=)
apiVersion: v1
kind: Secret
metadata:
  name: ovdas-secret
  namespace: ovdas
type: Opaque
data:
  postgres-password: b3ZkYXM=    # ovdas
  rabbitmq-password: b3ZkYXM=    # ovdas
